name: Deploy to cPanel

on:
  push:
    branches:
      - master  # Change this to your deployment branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: List build directory contents (for debugging)
      run: ls -la dist/

    - name: Verify build directory exists
      run: |
        if [ ! -d "dist" ]; then
          echo "Build directory does not exist"
          exit 1
        fi
        ls -la dist/

    - name: Upload production-ready build files
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: ${{ secrets.FTP_SERVER }}  # Your cPanel FTP server
        username: ${{ secrets.FTP_USERNAME }}  # Set in GitHub Secrets
        password: ${{ secrets.FTP_PASSWORD }}  # Set in GitHub Secrets
        protocol: ftp
        local-dir: dist/  # Ensure this ends with a /
